site_name: NCAA Basketball Analytics Project
site_description: Documentation for NCAA Basketball Analytics and Prediction Project
repo_url: https://github.com/tim-mcdonnell/ncaa-prediction-model
repo_name: NCAA Prediction Model

theme:
  name: material
  palette:
    primary: deep purple
    accent: amber
    scheme: slate
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: '{}'
  - pymdownx.tabbed
  - pymdownx.tasklist
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: material.extensions.emoji.twemoji
      emoji_generator: material.extensions.emoji.to_svg
  - attr_list
  - toc:
      permalink: true
      toc_depth: 3

nav:
  - Home: index.md
  - Architecture:
    - Overview: architecture/index.md
    - Data Pipeline: architecture/data-pipeline.md
    - Data Entities: architecture/data-entities.md
    - Data Directory Structure: architecture/data-directory-structure.md
    - Configuration Management: architecture/configuration-management.md
    - CLI Design: architecture/cli-design.md
    - Logging Strategy: architecture/logging-strategy.md
    - Development Phases: architecture/development-phases.md
  - Development Guides:
    - Overview: development-guides/index.md
    - How to Write Effective Tasks: development-guides/how-to-write-effective-tasks.md
    - Task Example: development-guides/task-example.md
  - API Reference:
    - ESPN API: espn-api-reference.md
    - ESPN Basketball APIs:
      - Scoreboard API: espn-api-documentation/basketball-scoreboard-api.md
      - Teams API: espn-api-documentation/basketball-teams-api.md

plugins:
  - search
  - mermaid2

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tim-mcdonnell/ncaa-prediction-model
