[project]
name = "ncaa-prediction-model"
version = "0.1.0"
description = "NCAA Basketball Prediction Model"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
dependencies = [
    "requests>=2.31.0",
    "pydantic>=2.6.1",
    "polars[pyarrow]>=0.19.13",
    "duckdb>=0.9.2",
    "scikit-learn>=1.3.2",
    "click>=8.1.3",
    "pyyaml>=6.0.1",
    "structlog>=23.1.0",
    "rich>=13.3.5",
    "httpx>=0.28.1",
    "tenacity>=9.0.0",
    "ruff>=0.11.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.3",
    "pytest-cov>=4.1.0",
    "ruff>=0.1.9",
    "mypy>=1.8.0",
    "mkdocs-material>=9.5.4",
    "pre-commit>=3.5.0"
]
viz = [
    "plotly>=5.18.0",
    "dash>=2.14.0",
    "kaleido>=0.2.1"
]
dl = [
    "torch>=2.0.0",
    "torchvision>=0.15.0",
    "lightning>=2.0.0"
]

[tool.pytest]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"

[tool.ruff]
target-version = "py311"
line-length = 100
select = ["E", "F", "B", "I", "N", "W", "UP", "ANN", "S", "A", "C4", "T20", "ARG", "ERA", "PD", "PL", "NPY", "RUF"]
ignore = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true

[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_defs = false
disallow_incomplete_defs = false
